/**
 * Byte-identical replay — ADR-0003's central guarantee.
 *
 * Two runs with the same seed and deterministic runtime must produce
 * the same sequence of events. Each previously-unfixed Math.random()
 * broke this (catalyst line, gather quantity); the seeded-RNG work
 * in a348e36 + 57bf52f closed those gaps. This test is the gatekeeper
 * that catches future regressions.
 *
 * We compare two runs by hashing a canonical projection of the events
 * table. Autogenerated ids (ulid / nanoid) and wall-clock timestamps
 * are intentionally excluded — they're expected to differ per run.
 * Anything inside `data_json` plus the event sequence (tick + type +
 * actor slot) must match exactly.
 */

import { describe, expect, it } from 'bun:test';
import { createHash } from 'node:crypto';
import { unlinkSync } from 'node:fs';
import type { Agent, Observation, TurnResult, World } from '@chronicle/core';
import { type AgentRuntimeAdapter, Engine, WorldStore } from '../src/index.js';

function makeWorld(id: string, seed: number): World {
  return {
    id,
    name: 'replay',
    description: '',
    systemPrompt: '',
    config: {
      atmosphere: 'parlor_drama', // triggers catalyst pool
      atmosphereTag: 'parlor_drama',
      scale: 'small',
      mapLayout: { kind: 'graph', locations: [] },
      defaultModelId: 'claude-haiku-4-5',
      defaultProvider: 'anthropic',
      reflectionFrequency: 100,
      dramaCatalystEnabled: true,
    },
    currentTick: 0,
    status: 'created',
    godBudgetTokens: null,
    tokensUsed: 0,
    tickDurationDescription: null,
    dayNightCycleTicks: null,
    createdAt: new Date('2026-01-01').toISOString(),
    createdByChronicle: null,
    forkFromTick: null,
    rngSeed: seed,
  };
}

function makeAgent(wId: string, id: string, name: string, locId: string | null): Agent {
  return {
    id,
    worldId: wId,
    name,
    persona: '',
    traits: {},
    privateState: null,
    alive: true,
    locationId: locId,
    mood: null,
    energy: 100,
    health: 100,
    tokensBudget: null,
    tokensSpent: 0,
    sessionId: null,
    sessionStateBlob: null,
    modelTier: 'haiku',
    provider: 'anthropic',
    modelId: 'claude-haiku-4-5',
    thinkingLevel: 'low',
    birthTick: 0,
    deathTick: null,
    parentIds: null,
    createdAt: new Date('2026-01-01').toISOString(),
  };
}

/**
 * Deterministic mock runtime that produces ZERO actions. This keeps
 * the drama score at 0 so the catalyst injector definitely fires
 * every 10 ticks (drama < 0.25 threshold), which is the main
 * seed-dependent path the test needs to exercise. Without this the
 * mock's speak/think/observe mix pushes drama above 0.25 and the
 * catalyst never runs, so seed differences don't show up in the
 * event stream.
 */
class SilentRuntime implements AgentRuntimeAdapter {
  async hydrate(): Promise<void> {}
  async takeTurn(agent: Agent, _obs: Observation, _tick: number): Promise<TurnResult> {
    // No action → engine records `agent_silent` (weight 0 in drama)
    return { agentId: agent.id, action: null, historyBlob: null, tokensSpent: agent.tokensSpent };
  }
  async applyAction(): Promise<void> {}
  async reflect(): Promise<string> {
    return 'reflection';
  }
  async shutdown(): Promise<void> {}
}

/** Project events into a shape safe to hash — drop auto-ids + wall clock. */
function canonicalize(events: Array<{ tick: number; eventType: string; data: unknown }>): string {
  return events
    .map((e) => {
      const { actorSlot, dataCanonical } = projectData(e.data, e.tick, e.eventType);
      return `${e.tick}|${e.eventType}|${actorSlot}|${dataCanonical}`;
    })
    .join('\n');
}

/**
 * Normalize a single event's data. For free-form fields (descriptions,
 * args), we keep them verbatim — that's what replay equivalence means.
 * Nothing in `data` is auto-generated per-run (all the randomness now
 * flows through seeded RNGs), so we compare the full JSON.
 */
function projectData(
  data: unknown,
  _tick: number,
  _eventType: string,
): { actorSlot: string; dataCanonical: string } {
  const d = data as Record<string, unknown>;
  // Action events carry `{action, args}`. Preserve.
  // Catalyst events carry `{description, atmosphereTag}`. Preserve.
  // God interventions carry `{description, compiled, effectResults}`.
  //   `compiled` is the raw intervention payload; keep. effectResults'
  //   details strings may reference auto-gen ids (grp_*, prp_*) — we
  //   strip those to the prefix so cross-run comparisons still match.
  if (d && typeof d === 'object' && 'effectResults' in d) {
    const r = d as { effectResults?: Array<{ ok?: boolean; detail?: string }> };
    const normResults = (r.effectResults ?? []).map((x) => ({
      ok: x.ok,
      // Strip the 6-char auto id tail from detail strings so
      // `rule_created:rul_abcdef` normalises to `rule_created:rul_*`.
      detail: (x.detail ?? '')
        .replace(/_[a-z0-9]{6,}$/i, '_<id>')
        .replace(/\b([a-z]+)_[a-z0-9]{4,}\b/gi, '$1_<id>'),
    }));
    return {
      actorSlot: 'system',
      dataCanonical: JSON.stringify({ ...r, effectResults: normResults }),
    };
  }
  return { actorSlot: 'any', dataCanonical: JSON.stringify(d ?? {}) };
}

async function runAndHash(seed: number, ticks: number): Promise<string> {
  const tmpPath = `/tmp/chronicle-replay-${Date.now()}-${Math.random().toString(36).slice(2, 8)}.db`;
  const store = await WorldStore.open(tmpPath);
  // IDs are pinned so the agent id doesn't enter the hash via natural
  // random generation. In a real sim ids are drawn at creation time;
  // replay from the event log restores the SAME ids, so comparing two
  // fresh creations IS allowed to vary on id only — but we pin here
  // to keep the test's signal narrow.
  const world = makeWorld(`chr_replay_${seed}`, seed);
  await store.createWorld(world);
  const locId = `loc_replay_${seed}`;
  await store.createLocation({
    id: locId,
    worldId: world.id,
    name: 'hall',
    description: '',
    x: null,
    y: null,
    parentId: null,
    affordances: [],
    metadata: {},
    spriteHint: null,
    createdAt: new Date('2026-01-01').toISOString(),
  });
  const alice = makeAgent(world.id, `agt_a_${seed}`, 'Alice', locId);
  const bob = makeAgent(world.id, `agt_b_${seed}`, 'Bob', locId);
  await store.createAgent(alice);
  await store.createAgent(bob);
  store.close();

  const runtime = new SilentRuntime();
  const engine = new Engine({ dbPath: tmpPath, worldId: world.id, runtime });
  await engine.init();
  await engine.run({ ticks });
  await engine.shutdown();

  const finalStore = await WorldStore.open(tmpPath);
  const events = await finalStore.getEventsInRange(world.id, 0, ticks + 10);
  finalStore.close();
  try {
    unlinkSync(tmpPath);
  } catch {}

  // We DO hash the tick + event_type + canonical data. We DO NOT
  // hash the event id (auto-increment) or actor_id (pinned above,
  // but in a general case it'd be a seeded-ulid).
  const canonical = canonicalize(events);
  return createHash('sha256').update(canonical).digest('hex');
}

describe('ADR-0003: byte-identical replay', () => {
  it('two runs with the same seed + deterministic runtime produce the same event hash', async () => {
    // 30 ticks is enough to guarantee the catalyst injector fires
    // (triggers every 10 ticks when drama < 0.25, and our mock runtime
    // doesn't generate drama > 0).
    const hashA = await runAndHash(42, 30);
    const hashB = await runAndHash(42, 30);
    expect(hashA).toBe(hashB);
  });

  it('different seeds produce different hashes', async () => {
    // Sanity — prove the hash is actually sensitive to seed, not
    // always-equal because we're hashing an empty projection.
    const hashA = await runAndHash(42, 30);
    const hashC = await runAndHash(43, 30);
    expect(hashA).not.toBe(hashC);
  });
});
